In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import make_regression

In [9]:
data = make_regression(n_samples=100, n_features=20, noise=10, random_state=42)

In [10]:
X = data[0]

In [11]:
y = data[1]

In [14]:
df = pd.DataFrame(X)

In [15]:
df.describe()

0           1           2           3           4           5   \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.066483   -0.090669    0.148793   -0.009252    0.066883    0.138678   
std      1.029991    0.977525    0.933608    0.895542    0.927696    0.923655   
min     -2.896255   -1.975467   -2.499406   -2.172670   -2.423879   -1.703382   
25%     -0.534866   -0.857052   -0.356271   -0.640109   -0.496090   -0.552580   
50%     -0.028445   -0.076344    0.178798   -0.016458    0.131194    0.145691   
75%      0.757704    0.531959    0.721849    0.564199    0.493497    0.839220   
max      2.290943    2.439752    2.526932    2.122156    3.137749    3.078881   

               6           7           8           9           10          11  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean    -0.020263    0.135566    0.048246    0.021527   -0.067366    0.116212   
std      0.978568    0.946059    0.904497    1.078934    0.849485    1.024664   
min     -1.748532   -1.760809   -2.471645   -3.241267   -2.703232   -2.198806   
25%     -0.766607   -0.655722   -0.585946   -0.650129   -0.555773   -0.659615   
50%     -0.020941    0.147305   -0.012252    0.044188   -0.010110    0.214404   
75%      0.622830    0.759989    0.654505    0.691722    0.466162    0.819755   
max      2.270693    2.455300    2.133033    2.560085    1.848956    2.601683   

               12          13          14          15          16          17  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.181512   -0.021257    0.140830    0.164645   -0.083936    0.011392   
std      1.045479    1.053048    0.921654    1.088579    1.063061    1.186164   
min     -2.619745   -2.591042   -2.872262   -2.152891   -2.696887   -2.940389   
25%     -0.531525   -0.676945   -0.435979   -0.608664   -0.945732   -0.684015   
50%      0.046091   -0.094711    0.174999    0.024079   -0.004435    0.091795   
75%      0.997346    0.648388    0.751524    0.860472    0.623706    0.821707   
max      2.644343    3.193108    2.720169    3.852731    2.170943    2.558199   

               18          19  
count  100.000000  100.000000  
mean    -0.013781   -0.032560  
std      1.007022    0.885011  
min     -2.151815   -2.650970  
25%     -0.775432   -0.554979  
50%     -0.022596    0.040263  
75%      0.584392    0.591680  
max      2.403416    1.765454

In [16]:
df.corr()

0         1         2         3         4         5         6   \
0   1.000000  0.004548 -0.129191  0.026306  0.009072 -0.172230 -0.159638   
1   0.004548  1.000000  0.114379 -0.003237 -0.071620  0.012699  0.028320   
2  -0.129191  0.114379  1.000000  0.128799 -0.025503 -0.017215 -0.043973   
3   0.026306 -0.003237  0.128799  1.000000 -0.269712 -0.075557  0.104791   
4   0.009072 -0.071620 -0.025503 -0.269712  1.000000  0.108145 -0.132818   
5  -0.172230  0.012699 -0.017215 -0.075557  0.108145  1.000000  0.029484   
6  -0.159638  0.028320 -0.043973  0.104791 -0.132818  0.029484  1.000000   
7   0.094057  0.041997 -0.050788  0.002972 -0.070478 -0.049503 -0.024925   
8   0.043956 -0.002852 -0.127256 -0.013555  0.134867  0.011433 -0.033633   
9  -0.076455  0.032839  0.094992  0.046317 -0.077725  0.112203  0.008165   
10  0.084357 -0.013414  0.042806  0.213739 -0.076422 -0.006337 -0.074601   
11  0.054632 -0.030318 -0.194916  0.041039 -0.168468  0.118695 -0.021824   
12 -0.039641 -0.070530  0.188536 -0.093565  0.043386  0.142316  0.011373   
13 -0.146794  0.107978 -0.089567 -0.073253  0.033541  0.148123  0.025203   
14 -0.012493 -0.117359 -0.046992 -0.101853  0.135511  0.062823  0.064736   
15 -0.092397 -0.035240 -0.076500  0.042289  0.107892  0.034785  0.073364   
16 -0.143799  0.040759  0.098150  0.120003 -0.034121 -0.017446 -0.049053   
17 -0.088933 -0.112353  0.049944 -0.021204 -0.074995 -0.025080 -0.163623   
18  0.134237 -0.058980 -0.027335 -0.159526 -0.037652  0.042316  0.053028   
19  0.082084  0.001684 -0.026813  0.015016 -0.051054  0.158593  0.116623   

          7         8         9         10        11        12        13  \
0   0.094057  0.043956 -0.076455  0.084357  0.054632 -0.039641 -0.146794   
1   0.041997 -0.002852  0.032839 -0.013414 -0.030318 -0.070530  0.107978   
2  -0.050788 -0.127256  0.094992  0.042806 -0.194916  0.188536 -0.089567   
3   0.002972 -0.013555  0.046317  0.213739  0.041039 -0.093565 -0.073253   
4  -0.070478  0.134867 -0.077725 -0.076422 -0.168468  0.043386  0.033541   
5  -0.049503  0.011433  0.112203 -0.006337  0.118695  0.142316  0.148123   
6  -0.024925 -0.033633  0.008165 -0.074601 -0.021824  0.011373  0.025203   
7   1.000000  0.009200  0.036454  0.088660  0.107441 -0.122975 -0.051254   
8   0.009200  1.000000  0.167277 -0.058522  0.128626  0.084063 -0.029720   
9   0.036454  0.167277  1.000000 -0.071686  0.073538 -0.067419 -0.007428   
10  0.088660 -0.058522 -0.071686  1.000000  0.003966 -0.028078 -0.058442   
11  0.107441  0.128626  0.073538  0.003966  1.000000 -0.144428 -0.023368   
12 -0.122975  0.084063 -0.067419 -0.028078 -0.144428  1.000000 -0.066726   
13 -0.051254 -0.029720 -0.007428 -0.058442 -0.023368 -0.066726  1.000000   
14  0.057023 -0.031667  0.154910 -0.165359  0.051117  0.174145  0.170635   
15 -0.082422 -0.048260  0.183953 -0.014784  0.040677  0.024779  0.002184   
16  0.115605 -0.127329 -0.077702 -0.072562 -0.024341 -0.171422  0.119435   
17 -0.271533 -0.013608  0.129965  0.042172  0.001608  0.156399 -0.121819   
18 -0.285803  0.111726  0.109297 -0.042557  0.182345  0.050355 -0.019511   
19 -0.092217  0.005402 -0.069252 -0.228384  0.043839  0.113035  0.024759   

          14        15        16        17        18        19  
0  -0.012493 -0.092397 -0.143799 -0.088933  0.134237  0.082084  
1  -0.117359 -0.035240  0.040759 -0.112353 -0.058980  0.001684  
2  -0.046992 -0.076500  0.098150  0.049944 -0.027335 -0.026813  
3  -0.101853  0.042289  0.120003 -0.021204 -0.159526  0.015016  
4   0.135511  0.107892 -0.034121 -0.074995 -0.037652 -0.051054  
5   0.062823  0.034785 -0.017446 -0.025080  0.042316  0.158593  
6   0.064736  0.073364 -0.049053 -0.163623  0.053028  0.116623  
7   0.057023 -0.082422  0.115605 -0.271533 -0.285803 -0.092217  
8  -0.031667 -0.048260 -0.127329 -0.013608  0.111726  0.005402  
9   0.154910  0.183953 -0.077702  0.129965  0.109297 -0.069252  
10 -0.165359 -0.014784 -0.072562  0.042172 -0.042557 -0.228384  
11  0.051117  0.040677 -0.024341  0.

In [19]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
LRM = LinearRegression()

In [23]:
LRM.fit(X_train, y_train)

LinearRegression()

In [37]:
LRM.score(X_test, y_test)

0.9909439489679167

In [25]:
R = Ridge(random_state=1)

In [26]:
R.fit(X_train, y_train)

Ridge(random_state=1)

In [36]:
R.score(X_test, y_test)

0.9904789221938927

In [28]:
L = Lasso()

In [29]:
L.fit(X_train, y_train)

Lasso()

In [35]:
L.score(X_test, y_test)

0.9908831106194036

In [40]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [41]:
sLRM = make_pipeline(
    StandardScaler(),
    LinearRegression()
)

In [42]:
sLRM.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [43]:
sLRM.score(X_test, y_test)

0.9909439489679167

In [44]:
sR = make_pipeline(
    StandardScaler(),
    Ridge(random_state=1)
)

In [45]:
sR.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('ridge', Ridge(random_state=1))])

In [46]:
sR.score(X_test, y_test)

0.9905354690251539

In [47]:
sL = sR = make_pipeline(
    StandardScaler(),
    Lasso()
)

In [48]:
sL.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [49]:
sL.score(X_test, y_test)

0.9908115288711693

In [51]:
LRM.coef_, LRM.intercept_

(array([ 5.67967903, 94.0225149 , 40.12270665,  0.79090588,  0.9906183 ,
        -0.5469879 , 12.57050486, 95.81154364, 80.48535992, 34.60293171,
         1.24152143,  1.369508  ,  2.27832545,  1.42568345, -0.88043861,
        27.44672945,  8.0178409 ,  1.29256083, -0.14809805, 54.66769774]),
 0.15977010359453558)

In [52]:
R.coef_, R.intercept_

(array([ 5.68924734, 93.09994602, 39.36005987,  1.14756297,  1.02144282,
        -0.62775045, 12.25023085, 94.09266962, 79.29074236, 34.74141513,
         0.92430242,  1.48025598,  2.67265389,  1.19701053, -1.05472982,
        27.09862818,  7.83816375,  0.92191753, -0.47784965, 53.52249458]),
 0.5004448429875126)

In [53]:
L.coef_, L.intercept_

(array([ 4.07762438e+00,  9.32616198e+01,  3.87967222e+01,  5.70299921e-01,
         0.00000000e+00, -0.00000000e+00,  1.08657966e+01,  9.44171841e+01,
         7.95454298e+01,  3.38262570e+01,  0.00000000e+00,  5.18969971e-02,
         1.11668702e+00,  0.00000000e+00, -0.00000000e+00,  2.67305631e+01,
         6.53106477e+00,  1.52012781e-01, -0.00000000e+00,  5.34713260e+01]),
 0.7160826066421784)